version: '3.8'

services:
  bookmarks_db:
    image: postgres:16-bookworm
    volumes:
      - bookmarks_database:/var/lib/postgresql/data/
    env_file:
      - ../.env
    restart: always
  bookmarks_redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
  bookmarks_backend:
    build:
      context: ..
      dockerfile: Dockerfile
    entrypoint: ./entrypoint_server.sh
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - bookmarks_db
    env_file:
      - ../.env
  bookmarks_worker:
    build:
      context: ..
      dockerfile: Dockerfile
    entrypoint: ./entrypoint_worker.sh
    restart: always
    env_file:
      - ../.env
    depends_on:
      - bookmarks_backend
  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static
      - media_volume:/var/html/media
    env_file:
      - ../.env
    depends_on:
      - bookmarks_backend

volumes:
  static_volume:
  media_volume:
  bookmarks_database: