# Generated by Django 4.2.7 on 2023-11-30 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookmarks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец коллекции",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель закладки",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="collections",
            field=models.ManyToManyField(
                related_name="bookmarks",
                through="bookmarks.CollectionBookmark",
                to="bookmarks.collection",
                verbose_name="Коллекции",
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("author", "title"), name="unique_collection_title"
            ),
        ),
    ]
