# Generated by Django 4.2.7 on 2023-11-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Картинка превью'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
