# Generated by Django 4.2.7 on 2023-11-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_alter_bookmark_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='link_type',
            field=models.CharField(choices=[('WS', 'website'), ('BK', 'book'), ('AR', 'article'), ('MC', 'music'), ('VD', 'video')], default='WS', max_length=2, verbose_name='Тип ссылки'),
        ),
    ]
