# Generated by Django 4.2.7 on 2023-11-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_alter_bookmark_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='link_type',
            field=models.CharField(choices=[('WS', 'Website'), ('BK', 'Book'), ('AR', 'Article'), ('MC', 'Music'), ('VD', 'Video')], default='WS', max_length=2, verbose_name='Тип ссылки'),
        ),
    ]
