# Generated by Django 4.2.7 on 2023-11-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0006_alter_bookmark_link_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-change_date', '-creation_date'], 'verbose_name': 'Закладка', 'verbose_name_plural': 'Закладки'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Коллекция закладок', 'verbose_name_plural': 'Коллекции закладок'},
        ),
        migrations.AlterModelOptions(
            name='collectionbookmark',
            options={'verbose_name': 'Коллекция связана с закладкой', 'verbose_name_plural': 'Коллекции связанные с закладками'},
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_collection_title'),
        ),
    ]
